# Generated by Django 3.2.4 on 2021-06-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('starts_at', models.DateField(null=True)),
                ('ends_at', models.DateField(null=True)),
                ('cover_image', models.ImageField(upload_to='series/%Y/%m/')),
                ('tags', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('preacher', models.CharField(max_length=225)),
                ('mime_type', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('size', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('tags', models.JSONField(null=True)),
                ('likes', models.PositiveIntegerField(default=0, null=True)),
                ('published', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.ImageField(upload_to='sermons/thumbs/%Y/%m/')),
            ],
        ),
    ]
