# Generated by Django 3.2.4 on 2021-06-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0002_sermon_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='ends_at',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='starts_at',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='tags',
            field=models.JSONField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='mime_type',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='published',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='tags',
            field=models.JSONField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
