# Generated by Django 3.2.4 on 2021-06-19 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0003_auto_20210612_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sermon',
            options={'ordering': ['-created_at', '-published']},
        ),
        migrations.RemoveField(
            model_name='series',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='tags',
        ),
    ]
