# Generated by Django 3.2.4 on 2021-06-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0004_auto_20210619_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'Series'},
        ),
        migrations.AlterField(
            model_name='series',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='series/%Y/%m/'),
        ),
    ]
