# Generated by Django 3.2.4 on 2021-06-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0007_auto_20210619_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='sermons/thumbs/%Y/%m/'),
        ),
    ]
