# Generated by Django 3.2.4 on 2021-06-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0008_alter_sermon_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='sermon_notes',
            field=models.FileField(blank=True, null=True, upload_to='static/sermon_notes/%Y/%m/', verbose_name='Sermon Notes'),
        ),
    ]
