# Generated by Django 3.2.4 on 2021-06-19 23:24

from django.db import migrations, models
import sermons.models
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0009_sermon_sermon_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='sermon_notes',
            field=models.FileField(blank=True, help_text='upload only pdf, word, txt files', null=True, upload_to='static/sermon_notes/%Y/%m/', validators=[sermons.models.validate_sermon_notes], verbose_name='Sermon Notes'),
        ),
    ]
