# Generated by Django 3.2.4 on 2021-06-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0010_auto_20210619_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='url',
            field=models.URLField(blank=True, help_text='Link to sermon resource (recording or video) if any', null=True),
        ),
    ]
