# Generated by Django 3.2.4 on 2021-07-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0013_auto_20210703_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='mime_type',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
