# Generated by Django 3.2.5 on 2021-08-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0014_alter_sermon_mime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='meta',
            field=models.JSONField(null=True),
        ),
    ]
