# Generated by Django 3.2.5 on 2021-08-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0015_sermon_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
