# Generated by Django 3.2.5 on 2021-08-21 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0016_alter_sermon_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermon',
            name='meta',
        ),
    ]
