# Generated by Django 3.2.7 on 2021-09-30 02:44

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0017_remove_sermon_meta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['-starts_at'], 'verbose_name_plural': 'Series'},
        ),
        migrations.AddField(
            model_name='preacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='preacher'),
        ),
        migrations.AlterField(
            model_name='series',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='series/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='description',
            field=djrichtextfield.models.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='description',
            field=djrichtextfield.models.RichTextField(null=True),
        ),
    ]
