version: "3.8"

services:
  web:
    restart: always
    build: .
    volumes:
      - ./hcn_cms:/app/hcn_cms
      - web-static:/app/hcn_cms/static
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000"
    env_file:
      - .env
    environment:
      DEBUG: "true"
    networks:
      - internal_web
      - internal_db
      - internal_memcached
    depends_on:
      - db

  nginx:
    restart: always
    build: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - web-static:/app/hcn_cms/static
    networks:
      - internal_web
    depends_on:
      - web

  db:
    image: postgres:13.3
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - internal_db
    volumes:
      - hcn_db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${MYSQL_DATABASE}
      POSTGRES_USER: ${MYSQL_USER}
      POSTGRES_PASSWORD: ${MYSQL_PASSWORD}

  memcache:
    image: memcached:1.6.9-alpine
    restart: always
    ports:
      - '11211'
    entrypoint:
      - memcached
      - -m 64
    networks:
      - internal_memcached

networks:
  internal_web:
  internal_db:
  internal_memcached:

volumes:
  web-static:
  web-django:
  hcn_db_volume:
    external: true


