version: "3.8"

services:
  web:
    restart: always
    build:
      context: ./hcn_cms
    volumes:
      - ./hcn_cms:/app/hcn_cms
      - web-static:/app/hcn_cms/static
      - web-media:/app/hcn_cms/media
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000"
    env_file:
      - .env
    environment:
      DEBUG: "true"
    networks:
      - internal_web
      - internal_db
      - internal_memcached
    depends_on:
      - db

  nginx:
    restart: always
    build: hcn_cms/docker/nginx
    ports:
      - "80:80"
    volumes:
      - web-static:/app/hcn_cms/static
      - web-media:/app/hcn_cms/media
    networks:
      - internal_web
    depends_on:
      - web

  db:
    image: postgres:13.3
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - internal_db
    volumes:
      - hcn_db_volume:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}

  memcache:
    image: memcached:1.6.9-alpine
    restart: always
    ports:
      - '11211'
    entrypoint:
      - memcached
      - -m 64
    networks:
      - internal_memcached

  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: unless-stopped
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - mailnetwork


networks:
  internal_web:
  internal_db:
  internal_memcached:
  mailnetwork:

volumes:
  web-static:
  web-media:
  web-django:
  hcn_db_volume:
    external: true


