# Generated by Django 3.2.4 on 2021-07-04 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('phone_model', models.CharField(max_length=255)),
                ('os_name', models.CharField(max_length=255)),
                ('os_version', models.CharField(max_length=255)),
                ('wifi', models.BooleanField(null=True)),
                ('bluetooth', models.BooleanField(null=True)),
                ('manufacturer', models.CharField(max_length=255)),
                ('screen_width', models.CharField(max_length=255)),
                ('screen_height', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_notification', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.device')),
            ],
        ),
    ]
