# Generated by Django 3.2.4 on 2021-07-07 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceconsent',
            name='id',
        ),
        migrations.AlterField(
            model_name='deviceconsent',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.device'),
        ),
    ]
