# Generated by Django 3.2.4 on 2021-07-10 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210710_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('is_member', models.BooleanField(default=False, null=True)),
                ('year_joined', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
